### ISSUE TITLE
info on gui

### ISSUE THREAD

**Issue by docop** [mpolitzer/grub-iso-multiboot#3]
Hi So quite a great soft and it could be usefull. Actually, can it be made usable as all text and list are so small that it's unreadable mostly.  i guess a setting is somewhere..?
thank in advance

**Comment by mpolitzer** [comment]
It can be made more readable and you have a couple of options.

1) If you are using a theme, there are a couple entries in `boot/grub/themes/starfield/theme.txt` regarding fonts that you can try to change:
```
message-font: "DejaVu Sans Regular 12"
terminal-font: "DejaVu Sans Regular 12"
        font = "DejaVu Sans Regular 10"
        item_font = "DejaVu Sans Regular 12"
        selected_item_font = "DejaVu Sans Bold 14"
        font = "DejaVu Sans Regular 12"
```

2) get rid of the `gfxmode` and go with text mode in `boot/grub/grub.cfg`.

**Comment by docop** [comment]
thanks a lot, appreciated
