### ISSUE TITLE
Would it be possible to keep ISOs on a different partition?

### ISSUE THREAD

**Issue by onnyyonn** [mpolitzer/grub-iso-multiboot#4]
FAT32 cannot have files more than 4 GB. But these days some ISOs are bigger than that. For example, Ubuntu 24.04. Would it be possible to keep /boot and /EFI on FAT32, but /boot/iso on a separate EXT4 partition, so that bigger ISOs are allowed?

**Comment by mpolitzer** [comment]
I didn't test this explicitly but the script[1] already scans all devices (the different partitions).
So in theory it should work if you put the isos on `/boot/iso` on a different partition without further changes.

I invite you to have a try and let me know it you encounter any problems.

ref.
[1] https://github.com/mpolitzer/grub-iso-multiboot/blob/master/boot/grub/script/autoiso.cfg#L123

**Comment by onnyyonn** [comment]
Thanks. I have tested it, and it worked.
